# Generated by Django 3.2.8 on 2021-11-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cathegories_cathegories_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cathegories',
            options={'verbose_name_plural': 'Cathegories'},
        ),
        migrations.RenameField(
            model_name='art',
            old_name='cathegories',
            new_name='cathegory',
        ),
    ]
