# Generated by Django 3.2.8 on 2021-11-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211104_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artlikes',
            options={'verbose_name_plural': 'Art likes'},
        ),
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name_plural': 'User follows'},
        ),
    ]
