# Generated by Django 3.2.8 on 2021-11-13 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.AddField(
            model_name='collection',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='art',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collected', to='api.art'),
        ),
    ]
